// <auto-generated />
#if !HELIOS_DEBUGGER_DISABLE
using System;
using UnityEngine;

internal static class HeliosGeneratedOptionsCatalog
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void Register()
    {
        HeliosDebugger.HeliosGeneratedOptions.Register(Type.GetType("HeliosDebuggerExample, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null", false));
    }
}
#endif
