using System.Collections;
using System.IO;
using System.Linq;
using System.Reflection;
using Astra.Helios.Editor;
using NUnit.Framework;

namespace Astra.Helios.Tests
{
    [UnityEngine.Scripting.APIUpdating.MovedFrom(false, "HeliosDebugger.Tests", "HeliosDebugger.EditMode.Tests")]
    public sealed class HeliosOptionsCatalogTests
    {
        [Test]
        public void LegacyCatalogBlocksBuildUntilRegenerated()
        {
            const string path = "Assets/HeliosDebuggerGenerated/HeliosGeneratedOptionsCatalog.g.cs";
            string previous = File.Exists(path) ? File.ReadAllText(path) : null;
            try
            {
                Directory.CreateDirectory(Path.GetDirectoryName(path));
                File.WriteAllText(path, "// <auto-generated />\n// HeliosDebugger.HeliosGeneratedOptions.Register");
                var error = Assert.Throws<UnityEditor.Build.BuildFailedException>(() => new HeliosDebuggerBuildValidator().OnPreprocessBuild(null));
                StringAssert.Contains("Regenerate", error.Message);
            }
            finally
            {
                if (previous == null) File.Delete(path); else File.WriteAllText(path, previous);
            }
        }

        [Test]
        public void GeneratedPreservationFileIsDiscoveredByUnity()
        {
            HeliosOptionsCatalogGenerator.Generate();
            const string path = "Assets/HeliosDebuggerGenerated/link.xml";
            Assert.IsTrue(File.Exists(path));
            Assert.IsFalse(File.Exists("Assets/HeliosDebuggerGenerated/HeliosGeneratedOptions.link.xml"));
            var stripper = typeof(UnityEditor.Editor).Assembly.GetType("UnityEditorInternal.AssemblyStripper");
            MethodInfo discover = stripper.GetMethod("GetUserBlacklistFiles", BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static);
            var paths = ((IEnumerable)discover.Invoke(null, null)).Cast<object>().Select(x => x.ToString());
            Assert.IsTrue(paths.Any(p => Path.GetFullPath(p) == Path.GetFullPath(path)));
        }
    }
}
