using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Security;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.Compilation;

namespace HeliosDebugger.Editor
{
    public static class HeliosOptionsCatalogGenerator
    {
        private const string DirectoryPath = "Assets/HeliosDebuggerGenerated";
        private const string CatalogPath = DirectoryPath + "/HeliosGeneratedOptionsCatalog.g.cs";
        private const string LinkPath = DirectoryPath + "/link.xml";
        private const string LegacyLinkPath = DirectoryPath + "/HeliosGeneratedOptions.link.xml";

        [MenuItem("Tools/HeliosDebugger/Regenerate Options Catalog")]
        public static void Generate()
        {
            IReadOnlyList<Type> types = CollectTypes();
            Directory.CreateDirectory(DirectoryPath);
            bool changed = WriteIfChanged(CatalogPath, BuildCatalog(types));
            changed |= WriteIfChanged(LinkPath, BuildLinkXml(types));
            if (File.Exists(LegacyLinkPath))
                changed |= AssetDatabase.DeleteAsset(LegacyLinkPath);
            if (changed)
                AssetDatabase.Refresh();
        }

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            EditorApplication.delayCall += Generate;
        }

        private static IReadOnlyList<Type> CollectTypes()
        {
            HashSet<string> playerAssemblyNames = new HashSet<string>(StringComparer.Ordinal);
            UnityEditor.Compilation.Assembly[] playerAssemblies =
                CompilationPipeline.GetAssemblies(AssembliesType.PlayerWithoutTestAssemblies);
            for (int i = 0; i < playerAssemblies.Length; i++)
                playerAssemblyNames.Add(playerAssemblies[i].name);

            List<Type> result = new List<Type>(TypeCache.GetTypesWithAttribute<HeliosOptionsAttribute>());
            result.RemoveAll(type =>
                type == null ||
                type.IsGenericTypeDefinition ||
                !playerAssemblyNames.Contains(type.Assembly.GetName().Name));
            result.Sort((left, right) =>
                string.Compare(left.AssemblyQualifiedName, right.AssemblyQualifiedName, StringComparison.Ordinal));
            return result;
        }

        private static string BuildCatalog(IReadOnlyList<Type> types)
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />")
                .AppendLine("#if !HELIOS_DEBUGGER_DISABLE")
                .AppendLine("using System;")
                .AppendLine("using UnityEngine;")
                .AppendLine()
                .AppendLine("internal static class HeliosGeneratedOptionsCatalog")
                .AppendLine("{")
                .AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]")
                .AppendLine("    private static void Register()")
                .AppendLine("    {");

            for (int i = 0; i < types.Count; i++)
            {
                string qualifiedName = EscapeCSharp(types[i].AssemblyQualifiedName);
                builder.Append("        HeliosDebugger.HeliosGeneratedOptions.Register(Type.GetType(\"")
                    .Append(qualifiedName)
                    .AppendLine("\", false));");
            }

            builder.AppendLine("    }")
                .AppendLine("}")
                .AppendLine("#endif");
            return builder.ToString();
        }

        private static string BuildLinkXml(IReadOnlyList<Type> types)
        {
            Dictionary<string, List<Type>> assemblies = new Dictionary<string, List<Type>>();
            for (int i = 0; i < types.Count; i++)
            {
                Type type = types[i];
                string assemblyName = type.Assembly.GetName().Name;
                if (!assemblies.TryGetValue(assemblyName, out List<Type> assemblyTypes))
                {
                    assemblyTypes = new List<Type>();
                    assemblies.Add(assemblyName, assemblyTypes);
                }
                assemblyTypes.Add(type);
            }

            List<string> names = new List<string>(assemblies.Keys);
            names.Sort(StringComparer.Ordinal);
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("<linker>");
            for (int assemblyIndex = 0; assemblyIndex < names.Count; assemblyIndex++)
            {
                string assemblyName = names[assemblyIndex];
                builder.Append("  <assembly fullname=\"")
                    .Append(SecurityElement.Escape(assemblyName))
                    .AppendLine("\">");
                List<Type> assemblyTypes = assemblies[assemblyName];
                for (int typeIndex = 0; typeIndex < assemblyTypes.Count; typeIndex++)
                {
                    builder.Append("    <type fullname=\"")
                        .Append(SecurityElement.Escape(assemblyTypes[typeIndex].FullName))
                        .AppendLine("\" preserve=\"all\" />");
                }
                builder.AppendLine("  </assembly>");
            }
            builder.AppendLine("</linker>");
            return builder.ToString();
        }

        private static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
                return false;
            File.WriteAllText(path, content, new UTF8Encoding(false));
            return true;
        }

        private static string EscapeCSharp(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
